-- First start only (run by the image's migrate.sh as postgres): the Auth server's database password.
-- Only a SCRAM-SHA-256 verifier is sent (generated by gen-secrets.sh): the image logs DDL statements, and
-- a verifier in a log line does not reveal the password. Changing the password later: run
-- `alter role supabase_auth_admin password '<new verifier>'` yourself and update .secrets/.env.
\set verifier `echo "$AUTH_DB_PASSWORD_SCRAM"`
alter role supabase_auth_admin with login password :'verifier';
