import 'server-only';

export { type SupabaseAuthLike, verifyClaims, verifyClaimsStrict } from './verify-claims';
export {
  type InvitationAcceptDeps,
  type InvitationAcceptOutcome,
  type InvitationLinkView,
  type InvitationSignUpClientLike,
  type InvitationViewer,
  INVITATION_TOKEN_PATTERN,
  InvitationAccountError,
  InvitationErrors,
  acceptInvitationAsSignedInUser,
  acceptInvitationWithNewAccount,
  acceptInvitationWithPassword,
  lookupInvitation,
  lookupInvitationLink,
  passwordLength,
  sessionEmail,
} from './invitation-accept';
export {
  type FactorLike,
  type MfaClientLike,
  type MfaDeps,
  type MfaOverview,
  type MfaVerification,
  type TotpSetup,
  MfaErrors,
  TOTP_ISSUER,
  getMfaOverview,
  removeTotp,
  startTotpSetup,
  verifyTotpCode,
} from './mfa';
export {
  type AuthClientLike,
  type AuthFlowDeps,
  type PasswordSession,
  type SessionTokens,
  type SignInOutcome,
  IdentityErrors,
  getSessionOrganizations,
  recordAudit,
  selectOrganization,
  signInWithPassword,
  signOut,
  signOutEndedSession,
  startPasswordSession,
} from './auth-flow';
export {
  type PasswordChangeDeps,
  type PasswordClientLike,
  type PasswordVerdict,
  type VerifierClientLike,
  PasswordErrors,
  changePassword,
  createPasswordVerifier,
} from './password';
export {
  type PasswordResetDelivery,
  type PasswordResetDeps,
  type PasswordResetRequestDeps,
  type RecoveryClientLike,
  type ResetEmailDelivery,
  PASSWORD_RESET_DELIVERY_ENV,
  PasswordResetErrors,
  RECOVERY_TOKEN_HASH_PATTERN,
  RESET_REQUEST_ANSWER_MS,
  completePasswordReset,
  readPasswordResetDelivery,
  requestPasswordReset,
} from './password-reset';
